### ISSUE TITLE
Get Kelli up to speed on making these quizzes

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/how-many-can-you-name#27]

**Comment by freejoe76** [comment]
@kelliparker you can close this when you feel adequately up to speed.

**Comment by kelliparker** [comment]
We've done how many can you name and multiple choice. Any other style we should talk about?

**Comment by freejoe76** [comment]
We've done things such as this in the past, http://interactive.nydailynews.com/2015/10/fanduel-faceoff/ , but I'm not sure we do those anymore.

**Comment by kelliparker** [comment]
With today's "how many" and this month's "multiple choice" I think I'm 90% up to speed with the quizzes. Should we add another type?

**Comment by kelliparker** [comment]
Please update the README with backend instructions. 👍
