### ISSUE TITLE
Produce and launch borough quiz #1

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/how-many-can-you-name#31]
For next week. We'll talk it through then.

1. Pick the borough
2. Put together the photo request
3. Produce the quiz
4. [some other things] Profit?
5. Launch!

**Comment by kelliparker** [comment]
Launching on June 1

**Comment by freejoe76** [comment]
🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕
