### ISSUE TITLE
Move the james-bond-movies and nfl quizzes to their own repo on bitbucket

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/how-many-can-you-name#35]
Once each have their own repo over there, remove them from this repo. https://bitbucket.org/account/user/nydailynews/projects/QUIZ

**Comment by freejoe76** [comment]
Also, create a repo on bitbucket for nato-member-countries-2017 and remove that from this repo.

**Comment by kelliparker** [comment]
Is that 3 repos or 1 with all of the "how many" quizzes inside? Can I clone project directories from www?

**Comment by kelliparker** [comment]
These are now in the Quizzes repo on BB.
